version: "3.8"

services:

# Complex microservice 

  #################################
  # ScheduleAggregation: The ScheduleAggregation microservice
  #################################
  ScheduleAggregation:
    build:
      context: ./ScheduleAggregation
      dockerfile: Dockerfile
    image: spm/scheduleaggregation:1.0
    restart: always
    ports: ["6003:6003"]
    environment:
      PYTHONUNBUFFERED: 1
